### ISSUE TITLE
How much more memory and computation does Universal Transformer require than vanilla Transformer for translation?

### ISSUE THREAD

**Issue by wenyong-h** [tensorflow/tensor2tensor#1232]
If i'm not misunderstanding, Universal Transformer uses bigger but shared encoder and decoder blocks, 
So if with same number of parameters for the whole model , each Universal Transformer block will need much more memory and computation than vanilla Transformer with same number of layers(or recurrent steps for UT).
Can you share the batch size  for Universal Transformer and vanilla Transformer during training with same gpu, and speed of inference?
@MostafaDehghani

**Comment by MostafaDehghani** [comment]
@wenyong-h 
In our experiments, the total number of trainable parameters for UT is same/similar to the corresponding transformer baseline. Yes, this leads to a network with a wider layer as we want to have the similar capacity/ expressiveness, in particular for the MT task where we need enough memorization.  A wider model means more computations (i.e. slightly slower training), but size-wise they are more or less the same.  We used the same batch size for training Transformer and the Universal Transformer (we used [```universal_transformer_base```](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer.py#L435) as hparams_set.

Right now, the Transformer is faster than UT at inference, specially because of a caching mechanism used for the transformer which make it faster than UT. [Using caching is in the TODOs](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/research/universal_transformer.py#L131) for improving the universal transformer's speed at inference. In theory, UT with adaptive halting has the potential of being faster than the Transformer at the inference.

**Comment by wenyong-h** [comment]
Thanks for your clear explanation, it is really helpful!

**Comment by dqqcasia** [comment]
universal_transformer_**base** inherits hparams_set from transformer_**big**, (see [universal_transformer_base](https://github.com/tensorflow/tensor2tensor/blob/52cefeb9bdf46682cf060c96822a14708def6515/tensor2tensor/models/research/universal_transformer.py#L436)), I do not understand why "All base results have the same number of parameters" in the paper. Could you tell me if I have missed any important information? Thanks very much!
