### ISSUE TITLE
How do you fix the unavailable dependency tf-agents in pip install?

### ISSUE THREAD

**Issue by wushaobo** [tensorflow/tensor2tensor#1504]
I think you have noticed that there is no release available for tf-agents pip library to install since Feb.  I notice it is still one of the dependencies in setup.py on master branch rather than the new name tf-agents-nightly.  
I am really wondering how your pip install on the 1.13.0 (latest version) can complete successfully.

**Comment by afrozenator** [comment]
Hi Shabo -- Thanks for raising this issue, I'll take a look.

**Comment by afrozenator** [comment]
Hi Shaobo

Since we don't use the tf-agents dependency I've removed it for now, we can add tf-agents-nightly once and if we start using something from that repo.

But I doubt that it was blocking anything? i.e. I was able to pip install tensor2tensor on a fresh virtualenv and maybe you should be able to as well?

Also will do a 1.13.1 release soon, in a day or so.

Will close the issue till then, feel free to reopen if you still have another issue?

Thanks!

**Comment by wushaobo** [comment]
Hi afrozenator,

Sorry for this late response.  I confirm the "pip install tensor2tensor" is successful with version 1.13.1 .

Thank you for fixing!
