### ISSUE TITLE
Increasing number of subwords in translation

### ISSUE THREAD

**Issue by ndvbd** [tensorflow/tensor2tensor#1774]
### Description

...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by ndvbd** [comment]
I would like to increase the subwords from 32k to 64k in the translation.

Is there a way to do it from the command line, in tensor2tensor.bin.t2t_datagen or tensor2tensor.bin.t2t_trainer, or should it be changed in the code (e.g. transformer_base) ?

**Comment by Mr-wang2016** [comment]
it is in data_generators/translate_enzh.py, def approx_vocab_size(self): return 2**15  # 32k

**Comment by ndvbd** [comment]
Thanks @Mr-wang2016, so the change is by code, not by cli parameters - got it. 
Do you know if there's any research about the importance of size of subwords vocab on the bleu performance?

**Comment by Mr-wang2016** [comment]
check https://arxiv.org/abs/1804.00247

**Comment by martinpopel** [comment]
There is no need to change the versioned code of `data_generators/translate_enzh.py`. You can define a new class
```
@registry.register_problem
class TranslateEnzhWmt64k(TranslateEnzhWmt32k):

  @property
  def approx_vocab_size(self):
    return 2**16
```
and register this class as described at https://github.com/tensorflow/tensor2tensor/#adding-your-own-components (using `--t2t_usr_dir`).
(Some `t2t-trainer` hyperparameters can be overridden from the command line, e.g.
`t2t-trainer --hparams="batch_size=8000,max_length=100,learning_rate_warmup_steps=8000,learning_rate_schedule=rsqrt_decay,optimizer=Adafactor"`, but I don't think this is possible for the vocabulary size, which is needed already in `t2t-datagen`.)

> check https://arxiv.org/abs/1804.00247

In this paper, we did not study the effect of vocabulary size. My guess is that for lower-resourced language pairs it is better to decrease the vocabulary size from the default 32k (at least you should make sure that the each subword occurs at least, say, 10 times in the training data). I have good experience with 32k for high-resource language pairs, even for a joint vocabulary for 9 languages and I doubt there will be any improvement when increasing the vocabulary size to 64k. It may cause more problems not only because of data sparseness but also because it takes more memory, you can afford smaller batch size and the training will be slower.

**Comment by ndvbd** [comment]
Thank you all!
