### ISSUE TITLE
What is the relationship between shards and minibatches in the wmt example?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#190]
Do shards work as minibatching at a higher level? If my training data for MT is pretty small (~100k sentences), can I do 1 shard at all? Thanks.

**Comment by lukaszkaiser** [comment]
When we say `shards` in data generator (`t2t-datagen`) it just means that we split large files into a number of smaller files. It's usually better to not have gigabyte-sized files, and reading from multiple files can be faster, that's why we do it. And yes, you can use 1 shard for 100k sentences, though I think having 10 is still fine too.

**Comment by austinmw** [comment]
@lukaszkaiser is there any utility for taking a single .record file and splitting it into multiple?
