### ISSUE TITLE
WMT Zh-En Translation Data Generation Error

### ISSUE THREAD

**Issue by agemagician** [tensorflow/tensor2tensor#194]
I tried to use the WMT Zh-En translation, however, it didn't work because two files in the test set was not correct:

```
_ZHEN_TEST_DATASETS = [[
    "http://data.statmt.org/wmt17/translation-task/dev.tgz",
    ("dev/newsdev2017-zhen-src.zh", "dev/newsdev2017-zhen-ref.en")
]]
```

I just downloaded the dev.tgz and found the file names are "dev/newsdev2017-zhen-src.zh.gsm" and "newsdev2017-zhen-ref.en.sgm".

I just renamed them and it did work.

I think you should rename them in your code.

**Comment by cshanbo** [comment]
Yes. 
We need to extract the plain text from the `sgm` file first. eg, download the tgz file and remove the xml tags in sgm files to generate plain text.

Because we don't want to add preprocessing codes into T2T. That's a remaining problem. See [PR](https://github.com/tensorflow/tensor2tensor/pull/151)

**Comment by lukaszkaiser** [comment]
I added a function to remove `sgm` tags to `data_generators/wmt.py` and corrected the problem with `zhen` generator in release 1.1.4. Give it a try guys, I hope it's better now. And of course please reopen if you still see any problem!
