### ISSUE TITLE
WSJ parsing can parse one child only

### ISSUE THREAD

**Issue by rainerschuster** [tensorflow/tensor2tensor#20]
It seems that words_and_tags_from_wsj_tree can parse wsj trees (lists) like
(A (B (C c)))
but not trees like
(A (B (C c d) e))

This is because it either assumes opening or closing parenthesis for each token.

**Comment by lukaszkaiser** [comment]
Hi Rainer. Yes, we don't parse (A B C), but I never saw this in Penn Treebank data. Or is it because my data was pre-processed? In any case, that'd be good to add, and I want to make sure you can train a parser on Penn Treebank without problems. As for the vocabulary you mentioned: we use word-pieces, even for parsing. We thought it might make results worse (as the mapping tokens -> POS tags isn't 1-1 any more), but it actually works very well, improving performance on unknown words. So give it a try. Would you be interested in making a PR to improve the `words_and_tags_from_wsj_tree` function? Please, let me know how your experiments are going!

**Comment by lukaszkaiser** [comment]
Hi Rainer, is this still a problem? I'm closing for now, please re-open if it's still wrong and give us more details what to repair (like a test case). Thanks!
