### ISSUE TITLE
problem translate_ende_wmt32k

### ISSUE THREAD

**Issue by vince62s** [tensorflow/tensor2tensor#269]
Quick question:
Why for this task does it need to generates a vocab.endefr.32768 file which requires some fr-en files of which the huge giga corpus. 
Can't we stick to en-de datasets ?
Thanks.

**Comment by martinpopel** [comment]
Yes, you can use just en-de datasets for creating the vocabulary. The advantage of endefr is that you can (later) use it for multilingual (multi-task) translation (and I guess this is the vocabulary which was used in the published papers).
Another question is what should be the default option. Here I agree just "en-de" would be better because of the download time, but I am not sure if it is important enough to change it now.

**Comment by vince62s** [comment]
thanks @martinpopel we also discussed this in gitter with @lukaszkaiser 
beyond the download time, if the problem is a single one, eg EN-DE, does it build the BPE model based on the 3 languages still ? if this is the case, I doubt this is the best scenario to replicate WMT for instance.

I understand the Multi lingual task , BTW, is it a multilingual single task or a multi lingual multi task, ie is it a single model in the end ? (like the multi way paper ?)

Anyhow, I would like to benchmark various toolkit on the same task, so the easier the better.

**Comment by lukaszkaiser** [comment]
Yes: we should have just the en-de problem as default (with just en-de vocab), and add a multilingual problem. Keeping this open until it's done, thanks for pushing on this guys!

**Comment by vince62s** [comment]
done here #370
