### ISSUE TITLE
What could lead to NaN?

### ISSUE THREAD

**Issue by skyw** [tensorflow/tensor2tensor#298]
Hi

It is not really issue. Just I'm curious, what could cause a NaN. I saw there is a math.isnan check for train_ppl.

**Comment by lukaszkaiser** [comment]
NaNs can be caused by various things: too high learning rates, bad initializations, other stuff that leads to the model exploding, but also bugs in ops, e.g., sparse_softmax_cross_entropy on GPU may return a NaN if some indices are out of vocabulary range. Often it's not easy to know, but it can sometimes be traced back to a reason.
