### ISSUE TITLE
Could you provide a consistent way to calculate BLEU?

### ISSUE THREAD

**Issue by skyw** [tensorflow/tensor2tensor#405]
It takes several steps to calculate BLEU. And it is not absolutely clear how BLEU should be calculated with the decoded text.

I would be nice to have a eval function just calculate the BLEU in the standard and correct way against given target.

**Comment by vince62s** [comment]
Just depending how you tokenize your text could lead to different value.
Google for "mt eval nist" or "multibleu" and you will find what you're looking for.

**Comment by lukaszkaiser** [comment]
Our BLEU functions are correct, use the utils/get...bleu.sh script for results comparable with publications.

**Comment by martinpopel** [comment]
I think no one uses the get_ende_bleu.sh script because two lines are hard-wrapped, so it cannot be executed as is: https://github.com/tensorflow/tensor2tensor/blob/097ea5f90c53c6ca5e5356f3295f1fc3093d7afb/tensor2tensor/utils/get_ende_bleu.sh#L15-L18
It would be nice to have a way how to compute the [official](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl) BLEU (both case sensitive and insensitive) for a beam-searched translation (of a possibly [avg_checkpointed](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/avg_checkpoints.py) model) **and see this curve in TensorBoard**. Now, when beam-search decoding is fast (4 minutes for 3000 sentences) it seems doable (I use `--save_checkpoints_secs=3600` that is one checkpoint&evaluation per hour).
It's on my todo list (together with character-based metrics, e.g. chrF3 or characTER), but unfortunately at the bottom of the list, which is rather a wish list:-).

**Comment by martinpopel** [comment]
I plan to make a PR with a script as described in my previous post.
So far I have a Python-only (no Perl) function which computes BLEU (including tokenization):
https://github.com/martinpopel/tensor2tensor/tree/bleu

**Comment by lukaszkaiser** [comment]
Would be great to have as a metric! We're also thinking about reporting all future results (on test) with https://github.com/mjpost/sacreBLEU -- what do you think guys?

**Comment by martinpopel** [comment]
I will send a PR soon (just tidying and testing).
Thanks for pointing to sacreBLEU - the idea of autodownloading test sets and reproducible BLEU is great. There is even a PR with chrF3. 
I am just missing international tokenization there (without this the correlation of BLEU with humans is much lower for languages with non-ascii characters, which includes also English with “typographic” quotes), but I can discuss this with @mjpost at sacreBLEU's github.

 > reporting all future results (on test) with https://github.com/mjpost/sacreBLEU

Yes. Even if sacreBLEU is integrated into T2T, I will still need most of my new code, which evaluates all checkpoints in a directory and stores the curve in TensorBoard events file (`--schedule=continuous_eval` evaluates just the last checkpoint and then waits for new ones, also it cannot use beam search, model averaging and I guess it would be difficult to make it use proper BLEU de/tokenization).

**Comment by martinpopel** [comment]
I did the PR: #436
