### ISSUE TITLE
Why append target_space_id embedding to inputs?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#424]
In the preparation for the encoder input, why append target_space_id embedding to inputs?
https://github.com/tensorflow/tensor2tensor/blob/75b75f2e2281101b9b3637e14ef519afd6a11b68/tensor2tensor/models/transformer.py#L407

**Comment by colmantse** [comment]
it is a token called side-constraint, which is proposed first by senrich to control politeness of output, it is then adopted by GNMT to do multi-lingual uni-model translation. By introducing the desired target language symbol without the source language symbol, the network learn to translate automatically to the target language, this also helps the network achieve zero shot translation.

**Comment by anglil** [comment]
Thanks for the pointer!

**Comment by anglil** [comment]
Still a little confused - How does a simple int64 scalar \in(1,32) affect the politeness of output? Also, since I'm doing another language not present in the existing spceID list, should I expand the target spce id embedding "vocab_size" from 32 to a larger number? Thanks!

**Comment by colmantse** [comment]
Treat it as an extra token, very much like everything else in the sequence. But instead, always occupy a certain position. I think t2t has left room for this, it is set to 32, but i remember only about 16 of it is occupied. Please check t2t-model or translate.py , you will see that list of integer. you may set it accordingly to accommodate your language, otherwise, i think it is also possible to do it at t2t_usr.
