### ISSUE TITLE
bug in TranslateEndeWmtBpe32k

### ISSUE THREAD

**Issue by liesun1994** [tensorflow/tensor2tensor#458]
Hello 
I am using   tensor2tensor (1.2.9)，and I am not sure if training is in a correct way . When I do decoding , error occurs （it always truncate the source sentences by symbol "."）: 
Examples are listed as follows : 
![image](https://user-images.githubusercontent.com/16813308/33546596-67763eaa-d91c-11e7-8e64-15c62369e0f7.png)
My configuration is transformer_base_single_gpu , transformer and all others are set to default . 
The bleu score only get 12.16 in newstest2014 (mirror question  #317 ).

**Comment by martinpopel** [comment]
Why do you create a new issue for the same problem as in #317?
As I wrote there, I believe the BPE vocab problem was fixed in t2t 1.3.0 by https://github.com/tensorflow/tensor2tensor/commit/7909c69c8f8d0708c32d3bba2f961cbb1ce29d0f.
You wrote there you will try it with t2t 1.3.0, but now you are reporting 1.2.9 again (or is it a typo?).

**Comment by liesun1994** [comment]
@martinpopel Thanks，I am running the program t2t 1.3.0 . Before getting the result , I printed the translation log to find the error occurs . I am afraid u can not receive the message in time , so a new issue is pulled . Sry ~

**Comment by liesun1994** [comment]
em..... I forgot my answers  in #317 ........
