### ISSUE TITLE
How to tf.Print tensors in t2t model?

### ISSUE THREAD

**Issue by faniuy** [tensorflow/tensor2tensor#499]
Did a lot of Googling, still can make it work.
Specifically, I tried to tf.Print encoder_outputs in _fast_decode in transformer.py.

    with tf.variable_scope("body"):
      encoder_output, encoder_decoder_attention_bias = dp(
          self.encode, inputs, features["target_space_id"], hparams,
          features=features)
    **encoder_output = encoder_output[0]**
    tf.Print(encoder_output, [tf.shape(encoder_output[2])], "encoder_output:")
    encoder_decoder_attention_bias = encoder_decoder_attention_bias[0]

**Comment by rsepassi** [comment]
So `tf.Print` returns a Tensor that you need to use in the subsequent graph so that the `Print` node actually gets run.

If you're just playing around and want to see Tensor values as they come through for experimentation/exploration/understanding, I'd suggest you use tensor2tensor in Eager mode. See this [notebook](https://goo.gl/wkHexj).

**Comment by faniuy** [comment]
Thank you for the reply. The code above is a small part of the transformer code.
The tensor encoder_output is definitely been used in the subsequent graph.
In fact I did a lot of manipulation on that tensor to change to result, that's why I want to check the value of the tensor.
