### ISSUE TITLE
*feature request* when or where to load the trained model.ckpt-file ? or can it be add by myself?

### ISSUE THREAD

**Issue by zxqchat** [tensorflow/tensor2tensor#752]
### Description

> …

### *TensorFlow* and *tensor2tensor* versions

> …tensorflow-gpu==1.4.0  tensorflow-tensorboard==0.4.0 tensor2tensor =v1.2.9

### feature request

> …the tensor2tensor can load the trained model.ckpt-file ? if have this features ,can you tell me the file and line(function)

##I find the code have performence to Restoring parameters in tensorflow estimator.py with the line 769 
 MonitoredTrainingSession

**Comment by martinpopel** [comment]
I am not sure what is your problem.
T2T supports loading models from checkpoints, of course (that's the main purpose of the checkpoints).
Both `t2t-decoder` and `t2t-trainer` take the `--output_dir` paramer. If this directory exists and contains a `checkpoint` file pointing to a particular `model.ckpt*` file, it will be loaded automatically (using `tf.estimator.Estimator`).
So with `t2t-decoder` you can resume an interrupted training (possibly changing some hyperparams which do not affect the model architecture).
Just note that the position in the training data is not saved in the checkpoint, so the training starts from the beginning of the training data again (or actually from a random position, but with a randseed fixed by default).

**Comment by zxqchat** [comment]
Thanks for your answer, I have tried to load my already trained model，it seems ok.

**Comment by EthannyDing** [comment]
@PlayDeep 
Did you figure out how to load model without first feeding any text data? I mean, Just load in model ckpt?

**Comment by PlayDeep** [comment]
@EthannyDing Yes

**Comment by EthannyDing** [comment]
@PlayDeep 
Sounds great!  can you please share your method of how to load the model?

**Comment by PlayDeep** [comment]
I am glad to share my code with you, but I am  a intern in a company and I can't show my code with my work laptop to avoid trouble. my personal computer placed in my school. You can find some useful code in this https://github.com/THUNLP-MT/THUMT

**Comment by EthannyDing** [comment]
Thanks for the reference, Xiaoqing. The work shown on this GitHub is awesome. However, I’m more concerned about how to restore pre-trained tensor2tensor model so I can make inference using it. Do you have any suggestions on how to do that? 

Really appreciate it for your response!

Best regards.

Sent from Mail for Windows 10

**Comment by PlayDeep** [comment]
@EthannyDing the reload method is the same no matter which model you want to load . read the restore function and write a new function in tensor2tensor.
